### PR TITLE
Working ingredients and lerna bootstrap

### PR DESCRIPTION
**Pull request by csperbeck**
Working Lerna Bootstrap and local inheritance system. Ingredient-ARM, ARM-Helper, Ingredient-Traffic-Manager, and Ingredient-WebApp-Container all need have local `npm install` to enable them. The reason is there are typing errors between similar classes of different modules. Possible version conflicts, or just needing an interface to extend to the conflicting class? Reviewed projects in the lerna repo, and they all followed the `package/` best practice, hence the reformat for ease of use.

### CODE REVIEW

**Comment by csperbeck** [comment]
Working compile... 
```
lerna run compile
lerna notice cli v3.11.1
lerna info Executing command in 10 packages: "npm run compile"
lerna info run Ran npm script 'compile' in '@azbake/core' in 4.1s:

> @azbake/core@0.1.17 compile C:\Users\csperbeck\source\repos\azure-bake\packages\core
> tsc -p ./src

lerna info run Ran npm script 'compile' in '@azbake/arm-helper' in 6.9s:

> @azbake/arm-helper@0.0.2 compile C:\Users\csperbeck\source\repos\azure-bake\packages\arm-helper
> tsc -p ./src

lerna info run Ran npm script 'compile' in '@azbake/ingredient-utils' in 6.7s:

> @azbake/ingredient-utils@0.0.15 compile C:\Users\csperbeck\source\repos\azure-bake\packages\ingredient-utils
> tsc -p ./src

lerna info run Ran npm script 'compile' in '' in 6.9s:

> @0.0.0 compile C:\Users\csperbeck\source\repos\azure-bake\packages\ingredient-template
> tsc -p ./src

lerna info run Ran npm script 'compile' in '@azbake/ingredient-script' in 7.1s:

> @azbake/ingredient-script@0.0.9 compile C:\Users\csperbeck\source\repos\azure-bake\packages\ingredient-script
> tsc -p ./src

lerna info run Ran npm script 'compile' in '@azbake/ingredient-arm' in 6.1s:

> @azbake/ingredient-arm@0.0.16 compile C:\Users\csperbeck\source\repos\azure-bake\packages\ingredient-arm
> tsc -p ./src

lerna info run Ran npm script 'compile' in '@azbake/ingredient-webapp-container' in 6.1s:

> @azbake/ingredient-webapp-container@0.0.2 compile C:\Users\csperbeck\source\repos\azure-bake\packages\ingredient-webapp-container
> tsc -p ./src

lerna info run Ran npm script 'compile' in '@azbake/ingredient-traffic-manager' in 6.3s:

> @azbake/ingredient-traffic-manager@0.0.2 compile C:\Users\csperbeck\source\repos\azure-bake\packages\ingredient-traffic-manager
> tsc -p ./src

lerna info run Ran npm script 'compile' in '@azbake/ingredient-host-names' in 6.5s:

> @azbake/ingredient-host-names@0.0.2 compile C:\Users\csperbeck\source\repos\azure-bake\packages\ingredient-host-names
> tsc -p ./src

lerna info run Ran npm script 'compile' in 'azure-bake' in 5.1s:

> azure-bake@0.1.18 compile C:\Users\csperbeck\source\repos\azure-bake\packages\system
> tsc -p ./src

lerna success run Ran npm script 'compile' in 10 packages in 22.4s:
lerna success - @azbake/arm-helper
lerna success - @azbake/core
lerna success - @azbake/ingredient-arm
lerna success - @azbake/ingredient-host-names
lerna success - @azbake/ingredient-script
lerna success -
lerna success - @azbake/ingredient-traffic-manager
lerna success - @azbake/ingredient-utils
lerna success - @azbake/ingredient-webapp-container
lerna success - azure-bake
```

**Comment by csperbeck** [comment]
Working lerna bootstrap...
```
lerna bootstrap
lerna notice cli v3.11.1
lerna notice filter excluding ["@azbake/arm-helper","@azbake/ingredient-arm","@azbake/ingredient-traffic-manager","@azbake/ingredient-webapp-container"]
lerna info filter [ '!@azbake/arm-helper',
lerna info filter   '!@azbake/ingredient-arm',
lerna info filter   '!@azbake/ingredient-traffic-manager',
lerna info filter   '!@azbake/ingredient-webapp-container' ]
lerna WARN bootstrap Installing local packages that do not match filters from registry
lerna info Bootstrapping 6 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 6 packages
C:\Users\csperbeck\source\repos\azure-bake [working_ingredients ↑1]> lerna run compile
lerna notice cli v3.11.1
lerna info Executing command in 10 packages: "npm run compile"
lerna info run Ran npm script 'compile' in '@azbake/core' in 3.9s:
```

**Comment by csperbeck** [comment]
Sample typing compile error from ARM-Helper....
```
 @azbake/arm-helper@0.0.2 compile C:\Users\csperbeck\source\repos\azure-bake\packages\arm-helper
> tsc -p ./src

src/arm-helper.ts(31,55): error TS2345: Argument of type 'TokenCredentialsBase' is not assignable to parameter of type 'ServiceClientCredentials'.
  Types of property 'signRequest' are incompatible.
    Type '(webResource: import("C:/Users/csperbeck/source/repos/azure-bake/packages/core/node_modules/@azure/ms-rest-js/es/lib/webResource").WebResource) => Promise<import("C:/Users/csperbeck/source/repos/azure-bake/packages/core/node_modules/@azure/ms-rest-js/es/lib/webResource").WebResource>' is not assignable to type '(webResource: import("C:/Users/csperbeck/source/repos/azure-bake/packages/arm-helper/node_modules/@azure/ms-rest-js/es/lib/webResource").WebResource) => Promise<import("C:/Users/csperbeck/source/repos/azure-bake/packages/arm-helper/node_modules/@azure/ms-rest-js/es/lib/webResource").WebResource>'.
      Types of parameters 'webResource' and 'webResource' are incompatible.
        Type 'import("C:/Users/csperbeck/source/repos/azure-bake/packages/arm-helper/node_modules/@azure/ms-rest-js/es/lib/webResource").WebResource' is not assignable to type 'import("C:/Users/csperbeck/source/repos/azure-bake/packages/core/node_modules/@azure/ms-rest-js/es/lib/webResource").WebResource'.
          Types of property 'headers' are incompatible.
            Type 'import("C:/Users/csperbeck/source/repos/azure-bake/packages/arm-helper/node_modules/@azure/ms-rest-js/es/lib/httpHeaders").HttpHeaders' is not assignable to type 'import("C:/Users/csperbeck/source/repos/azure-bake/packages/core/node_modules/@azure/ms-rest-js/es/lib/httpHeaders").HttpHeaders'.
              Types have separate declarations of a private property '_headersMap'.
src/arm-helper.ts(46,52): error TS7006: Parameter 'x' implicitly has an 'any' type.
```

**Comment by whilke** [comment]
Can you pull latest master and merge into your branch, and resubmitt? Looks like we had a sub-folder gitignore that included node-modules for the azdevops packages in your PR.

The merge should fix that up. You might need to make sure the node_modules folder within azdevops in your branch is deleted first.

**Comment by HomegrownDev** [comment]
Yes, sir. Will do.

**Comment by whilke** [comment]
Looks like you deleted all the package.lock files, which are needed. You also deleted a lot of needed files from the azdevops tasks.

**Comment by csperbeck** [comment]
Will fix ASAP. An accidental product of the work. Will merge master and `git mv` so that everything is where it is supposed to be.

Charlie Sperbeck
Senior Automation Engineer

On Feb 14, 2019 11:21 AM, Bill <notifications@github.com> wrote:

Looks like you deleted all the package.lock files, which are needed. You also deleted a lot of needed files from the azdevops tasks.

-

**Comment by csperbeck** [comment]
Re-creating another PR with proper items.

**Pull request closed without merging**
