### PR TITLE
Added VSCode development container

### PR DESCRIPTION
**Pull request by csperbeck**
Added a `devcontainer.json` and `Dockerfile` to allow for **ephemeral** dev and build environments with full docker compatiblity, npm, nodejs, typescript, and lerna pre-installed.

### CODE REVIEW

**Comment by whilke** [comment]
Is this for being able to debug bake deployments from within a docker container?

**Comment by whilke** [comment]
Should probably install kubectl as well since that's part of the normal bake runtime container, and needed for running k8-ingredients. Might even consider the azure cli packages if you ever need to run a azure check from within the container dev env.

**Comment by csperbeck** [comment]
Will add that. This is for having an ephemeral, pristine dev environment for bake development. Essentially a local deployment.

On Jun 11, 2019 7:24 PM, Bill <notifications@github.com> wrote:

Should probably install kubectl as well since that's part of the normal bake runtime container, and needed for running k8-ingredients. Might even consider the azure cli packages if you ever need to run a azure check from within the container dev env.

-

**Comment by whilke** [comment]
Yep, good idea.

**Comment by csperbeck** [comment]
@whilke The PR is ready and working. Takes a couple of minutes to reload the container, build, and link the ingredients for local debug.

**Comment by csperbeck** [comment]
Also includes `kubtctl` in the image.

**Comment by csperbeck** [comment]
@whilke @JasonPagel @jasonshamilton Any thoughts on this PR to give Bake Devs an ephemeral containerized environment free from contamination? Works beautiful with VSCode, and if you want to develop without it, just ignore it. exists.

**Pull request closed without merging**
